/**
 * @jest-environment jsdom
 */

import { describe, it, expect, jest, beforeEach } from '@jest/globals'
import { render, screen } from '@testing-library/react'
import '@testing-library/jest-dom'
import { ReportHeader } from '@/components/reports/ReportHeader'
import { ReportMetadata } from '@/lib/report-types'
import { REPORT_STYLES } from '@/lib/report-styles'

// We don't need to mock these components since we're testing their actual rendering

describe('ReportHeader Component', () => {
  const mockMetadata: ReportMetadata = {
    report_title: 'Test Security Report',
    generated_by: 'LEVANT AI Security Platform',
    generation_date: '2025-01-17T12:00:00Z',
    report_version: '3.0',
    analysis_duration_hours: 24,
  }

  beforeEach(() => {
    jest.clearAllMocks()
  })

  describe('Rendering', () => {
    it('should render the report title correctly', () => {
      render(<ReportHeader metadata={mockMetadata} />)
      
      const title = screen.getByRole('heading', { level: 1 })
      expect(title).toBeInTheDocument()
      expect(title).toHaveTextContent('Test Security Report')
    })

    it('should render the generated by information', () => {
      render(<ReportHeader metadata={mockMetadata} />)
      
      expect(screen.getByText('Generated by LEVANT AI Security Platform')).toBeInTheDocument()
    })

    it('should render the generation date with proper formatting', () => {
      render(<ReportHeader metadata={mockMetadata} />)
      
      // The date should be formatted as a readable string
      expect(screen.getByText(/Friday, January 17, 2025/)).toBeInTheDocument()
    })

    it('should render the analysis duration', () => {
      render(<ReportHeader metadata={mockMetadata} />)
      
      expect(screen.getByText('24 hour analysis')).toBeInTheDocument()
    })

    it('should render the report version', () => {
      render(<ReportHeader metadata={mockMetadata} />)
      
      expect(screen.getByText('Version 3.0')).toBeInTheDocument()
    })

    it('should render all icons', () => {
      render(<ReportHeader metadata={mockMetadata} />)
      
      // Check for actual SVG elements with lucide classes
      expect(document.querySelector('.lucide-calendar')).toBeInTheDocument()
      expect(document.querySelector('.lucide-clock')).toBeInTheDocument()
      expect(document.querySelector('.lucide-file-text')).toBeInTheDocument()
    })

    it('should render the separator', () => {
      render(<ReportHeader metadata={mockMetadata} />)
      
      // Check for the separator element by role
      expect(screen.getByRole('none')).toBeInTheDocument()
    })
  })

  describe('Styling', () => {
    it('should apply correct styles to the title element', () => {
      render(<ReportHeader metadata={mockMetadata} />)
      
      const title = screen.getByRole('heading', { level: 1 })
      // The title should use the pageTitle style from REPORT_STYLES
      expect(title).toHaveClass(REPORT_STYLES.typography.pageTitle.split(' ')[0]) // Check first class
    })

    it('should apply correct styles to the subtitle', () => {
      render(<ReportHeader metadata={mockMetadata} />)
      
      const subtitle = screen.getByText('Generated by LEVANT AI Security Platform')
      // Should have some styling classes applied
      expect(subtitle.className).toBeTruthy()
    })

    it('should have proper container structure', () => {
      render(<ReportHeader metadata={mockMetadata} />)
      
      const container = screen.getByRole('heading', { level: 1 }).closest('div')
      expect(container).toHaveClass('text-center')
      expect(container).toHaveClass('mb-8')
      expect(container).toHaveClass('print:mb-6')
    })
  })

  describe('Error Handling', () => {
    it('should handle invalid date gracefully', () => {
      const invalidMetadata = {
        ...mockMetadata,
        generation_date: 'invalid-date'
      }
      
      expect(() => render(<ReportHeader metadata={invalidMetadata} />)).not.toThrow()
    })

    it('should handle missing metadata properties gracefully', () => {
      const partialMetadata = {
        report_title: 'Test Report',
        generated_by: 'Test System',
        generation_date: '2025-01-17T12:00:00Z',
        report_version: '1.0',
        analysis_duration_hours: 1,
      } as ReportMetadata
      
      expect(() => render(<ReportHeader metadata={partialMetadata} />)).not.toThrow()
    })
  })

  describe('REPORT_STYLES Integration', () => {
    it('should use correct typography styles that exist in REPORT_STYLES', () => {
      // Verify that the styles we expect to use actually exist
      expect(REPORT_STYLES.typography.pageTitle).toBeDefined()
      expect(typeof REPORT_STYLES.typography.pageTitle).toBe('string')
      
      // This test will fail if typography.heading.h1 is used instead of pageTitle
      expect(REPORT_STYLES.typography.heading?.h1).toBeUndefined()
    })

    it('should not throw errors when accessing style properties', () => {
      // This is the critical test - it should not throw "Cannot read properties of undefined"
      expect(() => {
        const styles = REPORT_STYLES.typography.pageTitle
        expect(typeof styles).toBe('string')
      }).not.toThrow()
    })
  })
}) 