FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1
ENV TOKENIZERS_PARALLELISM=false

RUN chmod +x entrypoint.sh

CMD ["./entrypoint.sh"] 