import { NextRequest, NextResponse } from 'next/server'
import { extractReportData, isValidReportData } from '@/lib/report-types'
import { REPORT_STYLES, REPORT_ICONS, getSeverityBadgeClasses, getPriorityBadgeClasses } from '@/lib/report-styles'

export async function POST(request: NextRequest) {
  try {
    const { reportData, reportId } = await request.json()
    
    if (!reportData) {
      return NextResponse.json({ error: 'Report data is required' }, { status: 400 })
    }

    console.log('=== PDF GENERATION WITH COMPREHENSIVE ERROR HANDLING ===')
    
    // Extract and validate report data using our type system
    const extractedData = extractReportData(reportData)
    
    if (!extractedData) {
      return NextResponse.json({ error: 'Failed to extract report data' }, { status: 400 })
    }
    
    if (!isValidReportData(extractedData)) {
      console.warn('Report validation failed - using extracted data anyway')
    }

    // Helper functions for safe data operations
    const safeArray = (arr: any): any[] => Array.isArray(arr) ? arr : []
    const safeObject = (obj: any): Record<string, any> => (obj && typeof obj === 'object' && !Array.isArray(obj)) ? obj : {}
    const safeString = (str: any): string => (typeof str === 'string') ? str : ''
    const safeNumber = (num: any): number => (typeof num === 'number') ? num : 0

    const formatDate = (dateString: string) => {
      try {
      const date = new Date(dateString)
      return date.toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })
      } catch {
        return dateString || 'Unknown date'
      }
    }

    const formatBytes = (bytes: number) => {
      if (bytes === 0) return '0 Bytes'
      const k = 1024
      const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB']
      const i = Math.floor(Math.log(bytes) / Math.log(k))
      return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
    }

    // Protocol mapping
    const PROTOCOL_MAP: Record<number, string> = {
      1: 'ICMP', 2: 'IGMP', 6: 'TCP', 17: 'UDP', 41: 'IPv6',
      47: 'GRE', 50: 'ESP', 51: 'AH', 58: 'ICMPv6', 89: 'OSPF', 112: 'VRRP'
    }

    const getProtocolName = (protoKey: string, protoData: any): string => {
      if (protoData && typeof protoData.protocol_id === 'number') {
        const name = PROTOCOL_MAP[protoData.protocol_id]
        if (name) return name
      }
      const match = protoKey.match(/(?:protocol_)?(\d+)/i)
      if (match) {
        const id = Number(match[1])
        return PROTOCOL_MAP[id] || `Protocol ${id}`
      }
      return protoKey.toUpperCase()
    }

    // Render functions with comprehensive error handling
    const renderReportHeader = () => {
      const metadata = safeObject(extractedData.metadata)
      return `
        <div class="text-center mb-8 print:mb-6">
          <h1 class="text-3xl font-bold text-gray-900 mb-2 print:text-2xl">
            ${safeString(metadata.report_title) || 'Security Report'}
        </h1>
          <p class="text-lg text-gray-600 mb-4 print:text-base">
            Generated by ${safeString(metadata.generated_by) || 'LEVANT AI'}
        </p>
        <div class="flex items-center justify-center gap-6 text-sm text-gray-500 print:gap-4">
          <div class="flex items-center">
            ${REPORT_ICONS.calendar}
              ${formatDate(safeString(metadata.generation_date) || new Date().toISOString())}
          </div>
          <div class="flex items-center">
            ${REPORT_ICONS.clock}
              ${safeNumber(metadata.analysis_duration_hours)} hour analysis
          </div>
          <div class="flex items-center">
            ${REPORT_ICONS.fileText}
              Version ${safeString(metadata.report_version) || '1.0'}
          </div>
        </div>
        <div class="border-t border-gray-200 mt-8 mb-0 print:mt-6"></div>
      </div>
    `
    }

    const renderExecutiveSummary = () => {
      const summary = safeObject(extractedData.executive_summary)
      const keyFindings = safeArray(summary.key_findings)
      
      return `
        <section class="mb-8 print:mb-6">
          <h2 class="text-2xl font-bold text-gray-900 mb-4 print:text-xl">Executive Summary</h2>
        
        <div class="${REPORT_STYLES.grids.executive}">
          <div class="${REPORT_STYLES.cards.executive}">
            <div class="flex items-center mb-2">
              ${REPORT_ICONS.shield}
              <span class="text-sm font-medium text-gray-600">Risk Level</span>
            </div>
              <span class="${getSeverityBadgeClasses(safeString(summary.overall_risk_level) || 'UNKNOWN')}">
                ${safeString(summary.overall_risk_level) || 'UNKNOWN'}
            </span>
          </div>
          
          <div class="${REPORT_STYLES.cards.executive}">
            <div class="flex items-center mb-2">
              ${REPORT_ICONS.alertTriangle}
              <span class="text-sm font-medium text-gray-600">Critical Issues</span>
            </div>
            <span class="text-2xl font-bold text-gray-900">
                ${safeNumber(summary.critical_issues_count)}
            </span>
          </div>
          
          <div class="${REPORT_STYLES.cards.executive}">
            <div class="flex items-center mb-2">
              ${REPORT_ICONS.trendingUp}
              <span class="text-sm font-medium text-gray-600">Priority</span>
            </div>
            <span class="${REPORT_STYLES.badges.base} ${REPORT_STYLES.badges.outline}">
                ${safeString(summary.recommendations_priority) || 'LOW'}
            </span>
          </div>
        </div>

        <h3 class="${REPORT_STYLES.typography.subsectionTitle}">Key Findings</h3>
        <ul class="space-y-2">
            ${keyFindings.length > 0 
              ? keyFindings.map(finding => `
            <li class="flex items-start">
              <span class="w-2 h-2 bg-gray-400 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                  <span class="text-gray-700">${safeString(finding) || 'No finding details'}</span>
            </li>
              `).join('')
              : '<li class="text-gray-500">No key findings available</li>'
            }
        </ul>
      </section>
    `
    }

    const renderNetworkAnalysis = () => {
      const networkData = safeObject(extractedData.network_traffic_overview)
      const basicStats = safeObject(networkData.basic_stats)
      const topSources = safeArray(networkData.top_sources)
      const topDestinations = safeArray(networkData.top_destinations)
      const protocolBreakdown = safeObject(networkData.protocol_breakdown)
      const bandwidthStats = safeObject(networkData.bandwidth_stats)
      
              return `
          <section class="mb-8 print:mb-6">
            <h2 class="text-2xl font-bold text-gray-900 mb-4 print:text-xl">Network Traffic Analysis</h2>
        
        <div class="${REPORT_STYLES.grids.networkStats}">
          <div class="${REPORT_STYLES.cards.stats}">
            <h4 class="${REPORT_STYLES.typography.cardTitle}">Total Flows</h4>
            <p class="text-xl font-bold text-gray-900">
                ${safeNumber(basicStats.total_flows).toLocaleString()}
            </p>
          </div>
          
          <div class="${REPORT_STYLES.cards.stats}">
            <h4 class="${REPORT_STYLES.typography.cardTitle}">Total Data</h4>
            <p class="text-xl font-bold text-gray-900">
                ${formatBytes(safeNumber(basicStats.total_bytes))}
            </p>
          </div>
          
          <div class="${REPORT_STYLES.cards.stats}">
            <h4 class="${REPORT_STYLES.typography.cardTitle}">Total Packets</h4>
            <p class="text-xl font-bold text-gray-900">
                ${safeNumber(basicStats.total_packets).toLocaleString()}
            </p>
          </div>
          
          <div class="${REPORT_STYLES.cards.stats}">
            <h4 class="${REPORT_STYLES.typography.cardTitle}">Avg Bandwidth</h4>
            <p class="text-xl font-bold text-gray-900">
                ${safeNumber(bandwidthStats.average_mbps)} Mbps
            </p>
          </div>
        </div>

        <div class="${REPORT_STYLES.grids.traffic}">
          <div>
            <h3 class="${REPORT_STYLES.typography.subsectionTitle}">Top Traffic Sources</h3>
            <div class="space-y-2">
                ${topSources.length > 0
                  ? topSources.slice(0, 5).map(source => `
                <div class="flex items-center justify-between p-3 ${REPORT_STYLES.cards.traffic}">
                      <span class="${REPORT_STYLES.typography.monoText}">${safeString(source.ip) || 'Unknown'}</span>
                  <div class="text-right">
                        <div class="text-sm font-medium text-gray-900">${formatBytes(safeNumber(source.bytes))}</div>
                        <div class="${REPORT_STYLES.typography.captionText}">${safeNumber(source.flow_count)} flows</div>
                  </div>
                </div>
                  `).join('')
                  : '<div class="text-gray-500 p-3">No traffic sources available</div>'
                }
            </div>
          </div>

          <div>
            <h3 class="${REPORT_STYLES.typography.subsectionTitle}">Top Traffic Destinations</h3>
            <div class="space-y-2">
                ${topDestinations.length > 0
                  ? topDestinations.slice(0, 5).map(dest => `
                <div class="flex items-center justify-between p-3 ${REPORT_STYLES.cards.traffic}">
                      <span class="${REPORT_STYLES.typography.monoText}">${safeString(dest.ip) || 'Unknown'}</span>
                  <div class="text-right">
                        <div class="text-sm font-medium text-gray-900">${formatBytes(safeNumber(dest.bytes))}</div>
                        <div class="${REPORT_STYLES.typography.captionText}">${safeNumber(dest.flow_count)} flows</div>
                  </div>
                </div>
                  `).join('')
                  : '<div class="text-gray-500 p-3">No traffic destinations available</div>'
                }
            </div>
          </div>
        </div>

        <div>
          <h3 class="${REPORT_STYLES.typography.subsectionTitle}">Protocol Distribution</h3>
          <div class="${REPORT_STYLES.grids.protocols}">
              ${Object.keys(protocolBreakdown).length > 0
                ? Object.entries(protocolBreakdown).slice(0, 6).map(([protocol, data]) => {
                  const protocolData = safeObject(data)
                  return `
              <div class="p-3 ${REPORT_STYLES.cards.protocol}">
                <div class="flex items-center justify-between mb-1">
                        <span class="text-sm font-medium text-gray-900">${getProtocolName(protocol, protocolData)}</span>
                        ${protocolData.is_suspicious ? `
                    <span class="${getSeverityBadgeClasses('MEDIUM')}">
                      Suspicious
                    </span>
                  ` : ''}
                </div>
                <div class="${REPORT_STYLES.typography.captionText}">
                        ${safeNumber(protocolData.flow_count).toLocaleString()} flows • ${formatBytes(safeNumber(protocolData.total_bytes))}
                </div>
              </div>
                  `
                }).join('')
                : '<div class="text-gray-500 p-4">No protocol data available</div>'
              }
          </div>
        </div>
      </section>
    `
    }

    const renderSecurityFindings = () => {
      const securityFindings = safeObject(extractedData.security_findings)
      
      if (Object.keys(securityFindings).length === 0) {
        return `
      <section class="${REPORT_STYLES.layout.sectionContainer}">
        <h2 class="${REPORT_STYLES.typography.sectionTitle}">Security Analysis</h2>
            <div class="text-gray-500 p-4">No security findings available</div>
          </section>
        `
      }
      
      return `
        <section class="${REPORT_STYLES.layout.sectionContainer}">
          <h2 class="${REPORT_STYLES.typography.sectionTitle}">Security Analysis</h2>
          
          ${Object.entries(securityFindings).map(([category, data]) => {
            const findingData = safeObject(data)
            const potentialScanners = safeArray(findingData.potential_scanners)
            const highVolumeSources = safeArray(findingData.high_volume_sources)
          
          return `
            <div class="mb-6">
              <h3 class="${REPORT_STYLES.typography.subsectionTitle}">
                  ${safeString(category).replace(/_/g, ' ').toUpperCase()}
              </h3>
              
              <div class="${REPORT_STYLES.cards.security}">
                <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                  <div>
                    <span class="text-sm text-gray-600">Severity</span>
                      <span class="${getSeverityBadgeClasses(safeString(findingData.severity) || 'UNKNOWN')} ml-2">
                        ${safeString(findingData.severity) || 'UNKNOWN'}
                    </span>
                  </div>
                    ${findingData.count !== undefined ? `
                    <div>
                      <span class="text-sm text-gray-600">Count: </span>
                        <span class="font-medium">${safeNumber(findingData.count)}</span>
                    </div>
                  ` : ''}
                    ${findingData.matching_flows !== undefined ? `
                    <div>
                      <span class="text-sm text-gray-600">Matching Flows: </span>
                        <span class="font-medium">${safeNumber(findingData.matching_flows)}</span>
                    </div>
                  ` : ''}
                </div>
                
                  ${potentialScanners.length > 0 ? `
                  <div>
                    <h4 class="text-sm font-medium text-gray-900 mb-2">Potential Scanners Detected</h4>
                    <div class="space-y-1">
                        ${potentialScanners.slice(0, 5).map(scanner => {
                          const scannerData = safeObject(scanner)
                          return `
                        <div class="text-sm text-gray-700">
                              <span class="font-mono">${safeString(scannerData.source_ip) || safeString(scannerData.ip) || 'Unknown'}</span> - ${safeNumber(scannerData.ports_scanned) || safeNumber(scannerData.port_count)} ports scanned
                        </div>
                          `
                        }).join('')}
                    </div>
                  </div>
                ` : ''}
                
                  ${highVolumeSources.length > 0 ? `
                  <div>
                    <h4 class="text-sm font-medium text-gray-900 mb-2">High Volume Sources</h4>
                    <div class="space-y-1">
                        ${highVolumeSources.slice(0, 5).map(source => {
                          const sourceData = safeObject(source)
                          return `
                        <div class="text-sm text-gray-700">
                              <span class="font-mono">${safeString(sourceData.source_ip) || safeString(sourceData.ip) || 'Unknown'}</span> - ${safeNumber(sourceData.gb_sent) || safeNumber(sourceData.data_transferred)} GB transferred
                        </div>
                          `
                        }).join('')}
                    </div>
                  </div>
                ` : ''}
              </div>
            </div>
          `
        }).join('')}
      </section>
    `
    }

    const renderDataSourcesConfiguration = () => {
      const dataConfig = safeObject(extractedData.data_sources_and_configuration)
      
      if (Object.keys(dataConfig).length === 0) return ''
      
      const yafSensors = safeArray(dataConfig.yaf_ipfix_sensors)
      const threatSources = safeArray(dataConfig.threat_intelligence_sources)
      const analysisMethodology = safeObject(dataConfig.analysis_methodology)
      const configDetails = safeObject(dataConfig.configuration_details)
      const ipfixElements = safeArray(dataConfig.ipfix_information_elements)
      
      // Database icon SVG (consistent with browser component)
      const databaseIcon = `<svg class="h-4 w-4 text-gray-600 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 7v10c0 2.21 1.79 4 4 4h8c2.21 0 4-1.79 4-4V7c0-2.21-1.79-4-4-4H8c-2.21 0-4 1.79-4 4z"/>
      </svg>`
      
      return `
        <section class="mb-8 print:mb-6">
          <h2 class="text-2xl font-bold text-gray-900 mb-4 print:text-xl">Data Sources & Configuration</h2>
          
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <!-- Data Sources -->
            <div>
              <h3 class="text-lg font-semibold text-gray-900 mb-3">Data Sources</h3>
              <div class="space-y-3">
                <div class="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                    <div class="flex items-center mb-2">
                    ${databaseIcon}
                    <span class="font-medium text-gray-900">Primary Data Source</span>
                    </div>
                    <p class="text-sm text-gray-700 mb-1">
                    <strong>Source:</strong> ${safeString(dataConfig.primary_data_source) || 'Not specified'}
                    </p>
                  </div>
                
                ${yafSensors.length > 0 ? `
                  <div class="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                    <div class="flex items-center mb-2">
                      ${databaseIcon}
                      <span class="font-medium text-gray-900">YAF IPFIX Sensors</span>
                    </div>
                    <ul class="text-sm text-gray-700">
                      ${yafSensors.map(sensor => `
                        <li class="list-disc ml-4">${safeString(sensor) || 'Unknown sensor'}</li>
                `).join('')}
                    </ul>
                  </div>
                ` : ''}
                
                ${threatSources.length > 0 ? `
                  <div class="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                    <div class="flex items-center mb-2">
                      ${databaseIcon}
                      <span class="font-medium text-gray-900">Threat Intelligence Sources</span>
                    </div>
                    <ul class="text-sm text-gray-700">
                      ${threatSources.map(source => `
                        <li class="list-disc ml-4">${safeString(source) || 'Unknown source'}</li>
                      `).join('')}
                    </ul>
                  </div>
                ` : ''}
              </div>
            </div>

            <!-- Analysis Configuration -->
            <div>
              <h3 class="text-lg font-semibold text-gray-900 mb-3">Analysis Configuration</h3>
              <div class="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div class="space-y-3">
                  ${Object.keys(analysisMethodology).length > 0 ? `
                  <div>
                      <span class="text-sm font-medium text-gray-600">Normal Traffic Analysis:</span>
                      <p class="text-sm text-gray-900">${safeString(analysisMethodology.normal_traffic_analysis) || 'Not specified'}</p>
                  </div>
                  <div>
                      <span class="text-sm font-medium text-gray-600">Threat Detection:</span>
                      <p class="text-sm text-gray-900">${safeString(analysisMethodology.threat_detection) || 'Not specified'}</p>
                  </div>
                  <div>
                      <span class="text-sm font-medium text-gray-600">Comparison Scope:</span>
                      <p class="text-sm text-gray-900">${safeString(analysisMethodology.comparison_scope) || 'Not specified'}</p>
                    </div>
                  ` : ''}
                  
                  ${Object.keys(configDetails).length > 0 ? `
                    <div>
                      <span class="text-sm font-medium text-gray-600">Sampling Rate:</span>
                      <p class="text-sm text-gray-900">${safeString(configDetails.sampling_rate) || 'Not specified'}</p>
                    </div>
                    <div>
                      <span class="text-sm font-medium text-gray-600">Flow Timeout:</span>
                      <p class="text-sm text-gray-900">${safeString(configDetails.flow_timeout) || 'Not specified'}</p>
                    </div>
                    <div>
                      <span class="text-sm font-medium text-gray-600">Collection Method:</span>
                      <p class="text-sm text-gray-900">${safeString(configDetails.collection_method) || 'Not specified'}</p>
                    </div>
                  ` : ''}
                  
                  ${ipfixElements.length > 0 ? `
                    <div>
                      <span class="text-sm font-medium text-gray-600">IPFIX Elements:</span>
                    <p class="text-sm text-gray-900">
                        ${ipfixElements.length} information elements configured
                    </p>
                  </div>
                  ` : ''}
                </div>
              </div>
            </div>
          </div>
        </section>
      `
    }

    const renderComplianceGovernance = () => {
      const complianceData = safeObject(extractedData.compliance_and_governance)
      
      if (Object.keys(complianceData).length === 0) return ''
      
      const complianceStatus = safeArray(complianceData.compliance_status)
      const governancePolicies = safeObject(complianceData.governance_policies)
      const accessControls = safeArray(governancePolicies.access_controls)
      const riskAssessments = safeArray(complianceData.risk_assessments)
      
      const getComplianceClass = (status: string) => {
        switch (status.toLowerCase()) {
          case 'compliant':
            return REPORT_STYLES.badges.getSeverityClass('LOW')
          case 'non-compliant':
            return REPORT_STYLES.badges.getSeverityClass('HIGH')
          case 'partial':
            return REPORT_STYLES.badges.getSeverityClass('MEDIUM')
          default:
            return 'border-gray-200 text-gray-700 bg-gray-50'
        }
      }

      return `
        <section class="${REPORT_STYLES.layout.sectionContainer}">
          <h2 class="${REPORT_STYLES.typography.sectionTitle}">Compliance & Governance</h2>
          
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h3 class="${REPORT_STYLES.typography.subsectionTitle}">Compliance Status</h3>
              <div class="space-y-3">
                ${complianceStatus.length > 0 
                  ? complianceStatus.map(item => {
                    const complianceItem = safeObject(item)
                    const gaps = safeArray(complianceItem.gaps)
                    
                    return `
                  <div class="${REPORT_STYLES.cards.content}">
                    <div class="flex items-center justify-between mb-2">
                      <div class="flex items-center">
                            ${complianceItem.status && complianceItem.status.toLowerCase() === 'compliant' ? REPORT_ICONS.checkCircle : 
                              complianceItem.status && complianceItem.status.toLowerCase() === 'non-compliant' ? REPORT_ICONS.xCircle : REPORT_ICONS.alertCircle}
                            <span class="font-medium text-gray-900 ml-2">${safeString(complianceItem.framework) || 'Unknown Framework'}</span>
                      </div>
                          <span class="${getComplianceClass(safeString(complianceItem.status))} text-xs inline-flex items-center rounded-full border px-2.5 py-0.5 font-semibold">
                            ${safeString(complianceItem.status) || 'Unknown'}
                      </span>
                    </div>
                    <p class="text-sm text-gray-700 mb-1">
                          <strong>Score:</strong> ${safeNumber(complianceItem.score)}%
                    </p>
                    <p class="text-sm text-gray-700">
                          <strong>Last Assessment:</strong> ${complianceItem.last_assessment ? formatDate(complianceItem.last_assessment) : 'Unknown'}
                    </p>
                        ${gaps.length > 0 ? `
                      <div class="mt-2">
                        <span class="text-xs font-medium text-gray-600">Key Gaps:</span>
                        <ul class="text-xs text-gray-700 ml-4 mt-1">
                              ${gaps.slice(0, 3).map(gap => `<li class="list-disc">${safeString(gap) || 'Unknown gap'}</li>`).join('')}
                        </ul>
                      </div>
                    ` : ''}
                  </div>
                    `
                  }).join('')
                  : '<div class="text-gray-500 p-3">No compliance status available</div>'
                }
              </div>
            </div>

            <div>
              <h3 class="${REPORT_STYLES.typography.subsectionTitle}">Governance Policies</h3>
              <div class="${REPORT_STYLES.cards.content}">
                <div class="space-y-3">
                  <div>
                    <span class="text-sm font-medium text-gray-600">Data Retention:</span>
                    <p class="text-sm text-gray-900">${safeString(governancePolicies.data_retention) || 'Not specified'}</p>
                  </div>
                  ${accessControls.length > 0 ? `
                  <div>
                    <span class="text-sm font-medium text-gray-600">Access Controls:</span>
                    <ul class="text-sm text-gray-900 ml-4">
                        ${accessControls.map(control => `
                          <li class="list-disc">${safeString(control) || 'Unknown control'}</li>
                      `).join('')}
                    </ul>
                  </div>
                  ` : ''}
                  <div>
                    <span class="text-sm font-medium text-gray-600">Review Schedule:</span>
                    <p class="text-sm text-gray-900">${safeString(governancePolicies.review_schedule) || 'Not specified'}</p>
                  </div>
                  <div>
                    <span class="text-sm font-medium text-gray-600">Approval Authority:</span>
                    <p class="text-sm text-gray-900">${safeString(governancePolicies.approval_authority) || 'Not specified'}</p>
                  </div>
                </div>
              </div>

              ${riskAssessments.length > 0 ? `
              <div class="mt-4">
                <h4 class="text-sm font-medium text-gray-900 mb-2">Recent Risk Assessments</h4>
                <div class="space-y-2">
                    ${riskAssessments.slice(0, 3).map(assessment => {
                      const assessmentData = safeObject(assessment)
                      return `
                    <div class="text-sm border-l-2 border-gray-200 pl-3">
                      <div class="flex items-center justify-between">
                            <span class="font-medium text-gray-900">${safeString(assessmentData.type) || 'Unknown Assessment'}</span>
                            <span class="${REPORT_STYLES.badges.getSeverityClass(safeString(assessmentData.risk_level) || 'UNKNOWN')} text-xs inline-flex items-center rounded-full border px-2.5 py-0.5 font-semibold">
                              ${safeString(assessmentData.risk_level) || 'UNKNOWN'}
                        </span>
                      </div>
                          <p class="text-xs text-gray-600">${assessmentData.date ? formatDate(assessmentData.date) : 'Unknown date'}</p>
                    </div>
                      `
                    }).join('')}
                </div>
              </div>
              ` : ''}
            </div>
          </div>
        </section>
      `
    }

    const renderAIAnalysis = () => {
      const aiAnalysis = safeArray(extractedData.ai_analysis)
      
      if (aiAnalysis.length === 0) return ''
      
      return `
      <section class="${REPORT_STYLES.layout.sectionContainer}">
        <h2 class="${REPORT_STYLES.typography.sectionTitle}">AI Security Analysis</h2>
        
        <div class="space-y-4">
            ${aiAnalysis.map(item => {
              const analysisItem = safeObject(item)
              return `
            <div class="border border-gray-200 rounded-lg p-4 print:break-inside-avoid">
              <div class="flex items-start justify-between mb-3">
                <div class="flex items-center">
                  ${REPORT_ICONS.brain}
                      <span class="text-xs text-gray-500">MITRE ATT&CK: ${safeString(analysisItem.attack_technique) || 'Unknown'}</span>
                </div>
                <div class="flex items-center gap-2">
                      <span class="${getSeverityBadgeClasses(safeString(analysisItem.confidence_score) || 'UNKNOWN')} text-xs inline-flex items-center rounded-full border px-2.5 py-0.5 font-semibold">
                        ${Math.round((safeNumber(analysisItem.confidence_score) || 0) * 100)}% Confidence
                  </span>
                </div>
              </div>
              
              <div class="space-y-3">
                <div>
                  <h4 class="text-sm font-medium text-gray-900 mb-1 flex items-center">
                    ${REPORT_ICONS.target}
                    Finding
                  </h4>
                      <p class="text-sm text-gray-700 ml-5">${safeString(analysisItem.finding) || 'No finding details'}</p>
                </div>
                
                <div>
                  <h4 class="text-sm font-medium text-gray-900 mb-1">Business Impact</h4>
                      <p class="text-sm text-gray-700">${safeString(analysisItem.business_impact) || 'No impact details'}</p>
                </div>
                
                <div>
                  <h4 class="text-sm font-medium text-gray-900 mb-1">Recommended Action</h4>
                      <p class="text-sm text-gray-700">${safeString(analysisItem.recommended_action) || 'No action details'}</p>
                </div>
                
                <div class="flex items-center text-xs text-gray-500 pt-2 border-t border-gray-100">
                  ${REPORT_ICONS.clock}
                  <strong>Timeline:</strong> 
                      <span class="ml-1">${safeString(analysisItem.timeline) || 'Unknown'}</span>
                </div>
              </div>
            </div>
              `
            }).join('')}
        </div>
      </section>
    `
    }

    const renderRecommendations = () => {
      const recommendations = safeObject(extractedData.recommendations_and_next_steps)
      const prioritizedRecs = safeArray(recommendations.prioritized_recommendations)
      
      return `
      <section class="${REPORT_STYLES.layout.sectionContainer}">
        <h2 class="${REPORT_STYLES.typography.sectionTitle}">Recommendations</h2>
        
        <div class="space-y-4">
            ${prioritizedRecs.length > 0
              ? prioritizedRecs.map(rec => {
                const recData = safeObject(rec)
                return `
            <div class="${REPORT_STYLES.cards.recommendation}">
              <div class="flex items-start justify-between mb-2">
                      <h3 class="text-base font-semibold text-gray-900">${safeString(recData.category) || 'General'}</h3>
                      <span class="${getPriorityBadgeClasses(safeString(recData.priority) || 'LOW')}">
                        ${safeString(recData.priority) || 'LOW'}
                </span>
              </div>
              
              <p class="text-sm text-gray-700 mb-2">
                      <strong>Finding:</strong> ${safeString(recData.finding) || 'No finding details'}
              </p>
              
              <p class="text-sm text-gray-700 mb-2">
                      <strong>Recommendation:</strong> ${safeString(recData.recommendation) || 'No recommendation details'}
              </p>
              
              <div class="flex items-center gap-4 text-xs text-gray-500">
                      <span><strong>Effort:</strong> ${safeString(recData.estimated_effort) || 'Not specified'}</span>
                      <span><strong>Timeline:</strong> ${safeString(recData.timeline) || 'Not specified'}</span>
              </div>
            </div>
                `
              }).join('')
              : '<div class="text-gray-500 p-4">No recommendations available</div>'
            }
        </div>
      </section>
    `
    }

    // Generate complete CSS for PDF (same as before but ensuring it's complete)
    const generatePDFCSS = () => `
      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
      
      body {
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
      }
      
      /* Base Tailwind-like utilities */
      .min-h-screen { min-height: 100vh; }
      .bg-white { background-color: #ffffff; }
      .max-w-4xl { max-width: 56rem; }
      .mx-auto { margin-left: auto; margin-right: auto; }
      .p-8 { padding: 2rem; }
      .p-6 { padding: 1.5rem; }
      .p-4 { padding: 1rem; }
      .p-3 { padding: 0.75rem; }
      .mb-8 { margin-bottom: 2rem; }
      .mb-6 { margin-bottom: 1.5rem; }
      .mb-4 { margin-bottom: 1rem; }
      .mb-3 { margin-bottom: 0.75rem; }
      .mb-2 { margin-bottom: 0.5rem; }
      .mb-1 { margin-bottom: 0.25rem; }
      .mt-8 { margin-top: 2rem; }
      .mt-6 { margin-top: 1.5rem; }
      .mr-2 { margin-right: 0.5rem; }
      .mr-3 { margin-right: 0.75rem; }
      .ml-2 { margin-left: 0.5rem; }
      .ml-4 { margin-left: 1rem; }
      
      /* Typography */
      .text-3xl { font-size: 1.875rem; }
      .text-2xl { font-size: 1.5rem; }
      .text-xl { font-size: 1.25rem; }
      .text-lg { font-size: 1.125rem; }
      .text-base { font-size: 1rem; }
      .text-sm { font-size: 0.875rem; }
      .text-xs { font-size: 0.75rem; }
      .font-bold { font-weight: 700; }
      .font-semibold { font-weight: 600; }
      .font-medium { font-weight: 500; }
      .font-mono { font-family: ui-monospace, SFMono-Regular, "SF Mono", Monaco, Consolas, "Liberation Mono", "Courier New", monospace; }
      
      /* Colors */
      .text-gray-900 { color: #111827; }
      .text-gray-700 { color: #374151; }
      .text-gray-600 { color: #4b5563; }
      .text-gray-500 { color: #6b7280; }
      .bg-gray-50 { background-color: #f9fafb; }
      .border-gray-200 { border-color: #e5e7eb; }
      .border-t { border-top-width: 1px; }
      .border { border-width: 1px; }
      .rounded-lg { border-radius: 0.5rem; }
      .rounded { border-radius: 0.25rem; }
      .rounded-full { border-radius: 9999px; }
      
      /* Layout */
      .text-center { text-align: center; }
      .text-left { text-align: left; }
      .text-right { text-align: right; }
      .flex { display: flex; }
      .items-center { align-items: center; }
      .items-start { align-items: flex-start; }
      .justify-center { justify-content: center; }
      .justify-between { justify-content: space-between; }
      .gap-6 { gap: 1.5rem; }
      .gap-4 { gap: 1rem; }
      .gap-2 { gap: 0.5rem; }
      .space-y-2 > * + * { margin-top: 0.5rem; }
      .space-y-3 > * + * { margin-top: 0.75rem; }
      .space-y-4 > * + * { margin-top: 1rem; }
      
      /* Grid */
      .grid { display: grid; }
      .grid-cols-1 { grid-template-columns: repeat(1, minmax(0, 1fr)); }
      .grid-cols-2 { grid-template-columns: repeat(2, minmax(0, 1fr)); }
      .grid-cols-3 { grid-template-columns: repeat(3, minmax(0, 1fr)); }
      .grid-cols-4 { grid-template-columns: repeat(4, minmax(0, 1fr)); }
      
      /* Badges */
      .inline-flex { display: inline-flex; }
      .px-2-5 { padding-left: 0.625rem; padding-right: 0.625rem; }
      .py-0-5 { padding-top: 0.125rem; padding-bottom: 0.125rem; }
      
      /* Severity colors */
      .border-green-200 { border-color: #bbf7d0; }
      .text-green-700 { color: #15803d; }
      .bg-green-50 { background-color: #f0fdf4; }
      .border-yellow-200 { border-color: #fde68a; }
      .text-yellow-700 { color: #b45309; }
      .bg-yellow-50 { background-color: #fffbeb; }
      .border-red-200 { border-color: #fecaca; }
      .text-red-700 { color: #b91c1c; }
      .bg-red-50 { background-color: #fef2f2; }
      .border-blue-200 { border-color: #bfdbfe; }
      .text-blue-700 { color: #1d4ed8; }
      .bg-blue-50 { background-color: #eff6ff; }
      
      /* Utility */
      .w-2 { width: 0.5rem; }
      .h-2 { height: 0.5rem; }
      .h-4 { width: 1rem; height: 1rem; }
      .w-4 { width: 1rem; height: 1rem; }
      .h-5 { width: 1.25rem; height: 1.25rem; }
      .w-5 { width: 1.25rem; height: 1.25rem; }
      .flex-shrink-0 { flex-shrink: 0; }
      .list-disc { list-style-type: disc; }
      
      /* Additional card styling */
      .shadow-sm { box-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.05); }
      .gap-6 { gap: 1.5rem; }
      .p-6 { padding: 1.5rem; }
      .mb-3 { margin-bottom: 0.75rem; }
      
      /* Print styles */
      @media print {
        .print\\:p-6 { padding: 1.5rem !important; }
        .print\\:mb-6 { margin-bottom: 1.5rem !important; }
        .print\\:mt-6 { margin-top: 1.5rem !important; }
        .print\\:text-2xl { font-size: 1.5rem !important; }
        .print\\:text-xl { font-size: 1.25rem !important; }
        .print\\:text-base { font-size: 1rem !important; }
        .print\\:gap-4 { gap: 1rem !important; }
        .print\\:grid-cols-3 { grid-template-columns: repeat(3, minmax(0, 1fr)) !important; }
        .print\\:grid-cols-4 { grid-template-columns: repeat(4, minmax(0, 1fr)) !important; }
        .print\\:border { border: 1px solid #e5e7eb !important; }
        .print\\:bg-white { background-color: white !important; }
        .print\\:break-inside-avoid { page-break-inside: avoid !important; }
      }
    `

    // Generate complete HTML with comprehensive error handling
    const htmlContent = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${safeString(extractedData.metadata?.report_title) || 'Security Report'} - PDF Export</title>
        <style>
          ${generatePDFCSS()}
        </style>
      </head>
      <body class="min-h-screen bg-white">
        <div class="max-w-4xl mx-auto p-8 print:p-6">
          ${renderReportHeader()}
          ${renderExecutiveSummary()}
          <div class="border-t border-gray-200 mb-8 print:mb-6"></div>
          ${renderNetworkAnalysis()}
          <div class="border-t border-gray-200 mb-8 print:mb-6"></div>
          ${renderSecurityFindings()}
          <div class="border-t border-gray-200 mb-8 print:mb-6"></div>
          ${renderDataSourcesConfiguration()}
          ${extractedData.data_sources_and_configuration ? '<div class="border-t border-gray-200 mb-8 print:mb-6"></div>' : ''}
          ${renderComplianceGovernance()}
          ${extractedData.compliance_and_governance ? '<div class="border-t border-gray-200 mb-8 print:mb-6"></div>' : ''}
          ${renderAIAnalysis()}
          ${extractedData.ai_analysis && extractedData.ai_analysis.length > 0 ? '<div class="border-t border-gray-200 mb-8 print:mb-6"></div>' : ''}
          ${renderRecommendations()}
          
          <div class="mt-12 pt-6 border-t border-gray-200 text-center text-sm text-gray-500 print:mt-8">
            <p>This report was automatically generated by LEVANT AI Security Platform</p>
            <p class="mt-1">Report ID: ${safeString(reportId) || 'Unknown'}</p>
          </div>
        </div>
      </body>
      </html>
    `

    // Generate PDF using Puppeteer with comprehensive error handling
    try {
      let puppeteer
      try {
        puppeteer = require('puppeteer')
      } catch (error) {
        console.error('Puppeteer not available, returning HTML content')
        return new NextResponse(htmlContent, {
          headers: {
            'Content-Type': 'text/html',
          }
        })
      }

      const browser = await puppeteer.launch({
        headless: true,
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--disable-gpu',
          '--disable-web-security',
          '--disable-features=VizDisplayCompositor',
          '--no-first-run',
          '--no-default-browser-check'
        ]
      })

      const page = await browser.newPage()
      
      await page.setContent(htmlContent, {
        waitUntil: ['domcontentloaded', 'networkidle0'],
        timeout: 30000
      })

      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: {
          top: '0.5in',
          right: '0.5in',
          bottom: '0.5in',
          left: '0.5in'
        },
        preferCSSPageSize: true
      })

      await browser.close()

      console.log('PDF generated successfully with comprehensive error handling')

      return new NextResponse(pdfBuffer, {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="security-report-${safeString(reportId) || 'unknown'}.pdf"`
        }
      })

    } catch (puppeteerError) {
      console.error('Puppeteer PDF Generation Error:', puppeteerError)
      
      // Fallback: Return HTML content if PDF generation fails
      console.log('Falling back to HTML content due to PDF generation failure')
      return new NextResponse(htmlContent, {
        headers: {
          'Content-Type': 'text/html',
          'Content-Disposition': `attachment; filename="security-report-${safeString(reportId) || 'unknown'}.html"`
        }
      })
    }

  } catch (error) {
    console.error('PDF Generation Error:', error)
    return NextResponse.json(
      { 
        error: 'Failed to generate PDF', 
        details: error instanceof Error ? error.message : 'Unknown error',
        fallback: 'Try downloading as JSON instead'
      },
      { status: 500 }
    )
  }
} 