import React from 'react'
import { Calendar, Clock, FileText } from 'lucide-react'
import { Separator } from '@/components/ui/separator'
import { REPORT_STYLES } from '@/lib/report-styles'
import { ReportMetadata } from '@/lib/report-types'

interface ReportHeaderProps {
  metadata: ReportMetadata
}

export function ReportHeader({ metadata }: ReportHeaderProps) {
  const formatDate = (dateString: string) => {
    const date = new Date(dateString)
    return date.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  }

  return (
    <div className="text-center mb-8 print:mb-6">
      <h1 className={REPORT_STYLES.typography.pageTitle}>
        {metadata.report_title}
      </h1>
      <p className={REPORT_STYLES.typography.pageSubtitle}>
        Generated by {metadata.generated_by}
      </p>
      <div className="flex items-center justify-center gap-6 text-sm text-gray-500 print:gap-4">
        <div className="flex items-center">
          <Calendar className="h-4 w-4 mr-2" />
          {formatDate(metadata.generation_date)}
        </div>
        <div className="flex items-center">
          <Clock className="h-4 w-4 mr-2" />
          {metadata.analysis_duration_hours} hour analysis
        </div>
        <div className="flex items-center">
          <FileText className="h-4 w-4 mr-2" />
          Version {metadata.report_version}
        </div>
      </div>
      <Separator className="mt-8 mb-0 print:mt-6" />
    </div>
  )
} 