/**
 * Comprehensive TypeScript interfaces for LEVANT AI Security Reports
 * 
 * These interfaces exactly match the structure generated by report_generator.py
 * and include ALL sections, fields, and data types from the Python implementation.
 * 
 * CRITICAL: Keep this synchronized with report_generator.py structure.
 * When Python generator adds new fields, update these interfaces accordingly.
 */

// ===========================================
// CORE REPORT STRUCTURE
// ===========================================

/**
 * Complete report data structure matching report_generator.py output
 */
export interface ReportData {
  // Core sections (always present)
  metadata: ReportMetadata;
  executive_summary: ExecutiveSummary;
  network_traffic_overview: NetworkTrafficOverview;
  security_findings: SecurityFindings;
  recommendations_and_next_steps: RecommendationsAndNextSteps;
  
  // Additional sections (may be present in comprehensive reports)
  data_sources_and_configuration?: DataSourcesAndConfiguration;
  compliance_and_governance?: ComplianceAndGovernance;
  ai_analysis?: AIAnalysis[];
}

// ===========================================
// METADATA SECTION
// ===========================================

export interface ReportMetadata {
  report_title: string;
  reporting_period: string;
  generated_by: string;
  generation_date: string;
  report_version: string;
  analysis_duration_hours: number;
  analysis_scope: string;
  threat_detection_method: string;
  
  // Optional fields from automation
  user_netid?: string;
  custom_query?: string;
  report_type?: string;
  automation_info?: {
    is_automated: boolean;
    generation_type: 'scheduled' | 'user_requested' | 'manual';
    schedule?: string;
    frontend_integration?: boolean;
    api_accessible?: boolean;
    requested_by?: string;
  };
}

// ===========================================
// EXECUTIVE SUMMARY SECTION
// ===========================================

export interface ExecutiveSummary {
  overall_risk_level: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  key_findings: string[];
  critical_issues_count: number;
  recommendations_priority: 'IMMEDIATE' | 'SCHEDULED' | 'ONGOING' | 'LOW';
  
  // Optional additional fields
  total_threats_detected?: number;
  risk_score?: number;
}

// ===========================================
// NETWORK TRAFFIC OVERVIEW SECTION
// ===========================================

export interface NetworkTrafficOverview {
  basic_stats: BasicNetworkStats;
  top_sources: TrafficSource[];
  top_destinations: TrafficDestination[];
  protocol_breakdown: Record<string, ProtocolInfo>;
  bandwidth_stats: BandwidthStats;
  
  // Optional detailed analysis
  port_analysis?: PortAnalysis;
  malicious_ports_detected?: boolean;
}

export interface BasicNetworkStats {
  total_flows: number;
  total_bytes: number;
  total_packets: number;
  avg_duration: number;
  avg_bandwidth?: number;
}

export interface TrafficSource {
  ip: string;
  bytes: number;
  flow_count: number;
  threat_intel?: ThreatIntelligence;
}

export interface TrafficDestination {
  ip: string;
  bytes: number;
  flow_count: number;
  threat_intel?: ThreatIntelligence;
}

export interface ThreatIntelligence {
  is_malicious: boolean;
  threat_type: string | null;
  confidence: number;
  sources: string[];
}

export interface ProtocolInfo {
  protocol_id: number;
  flow_count: number;
  total_bytes: number;
  is_suspicious: boolean;
  protocol_name?: string;
  
  // Optional service information
  service?: string;
  is_malicious?: boolean;
}

export interface BandwidthStats {
  total_bytes: number;
  average_mbps: number;
  duration_seconds: number;
  
  // Extended bandwidth metrics
  total_bits?: number;
  average_bps?: number;
  average_gbps?: number;
}

export interface PortAnalysis {
  top_ports: PortInfo[];
  malicious_ports_detected: boolean;
}

export interface PortInfo {
  port: number;
  flow_count: number;
  total_bytes: number;
  service: string;
  is_malicious: boolean;
}

// ===========================================
// SECURITY FINDINGS SECTION
// ===========================================

export interface SecurityFindings {
  // Core security analysis categories
  malicious_pattern_matches: MaliciousPatternMatches;
  honeypot_pattern_matches: HoneypotPatternMatches;
  suspicious_connections: SuspiciousConnections;
  port_scanning: PortScanning;
  data_exfiltration: DataExfiltration;
  unusual_protocols: UnusualProtocols;
  threat_intelligence_matches: ThreatIntelligenceMatches;
  
  // Allow for additional dynamic categories
  [key: string]: SecurityFindingCategory;
}

export interface SecurityFindingCategory {
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  count?: number;
  matching_flows?: number;
  description?: string;
  findings?: string[];
}

export interface MaliciousPatternMatches extends SecurityFindingCategory {
  pattern_matches: any[];
  known_malicious_ips: number;
  matching_flows: number;
}

export interface HoneypotPatternMatches extends SecurityFindingCategory {
  honeypot_matches: any[];
  known_honeypot_ips: number;
  known_honeypot_ports: number;
  matching_patterns: number;
}

export interface SuspiciousConnections extends SecurityFindingCategory {
  suspicious_pairs: SuspiciousConnectionPair[];
  count: number;
}

export interface SuspiciousConnectionPair {
  source_ip: string;
  destination_ip: string;
  connection_count: number;
}

export interface PortScanning extends SecurityFindingCategory {
  potential_scanners: PortScanner[];
  count: number;
}

export interface PortScanner {
  source_ip: string;
  ports_scanned: number;
}

export interface DataExfiltration extends SecurityFindingCategory {
  high_volume_sources: HighVolumeSource[];
  count: number;
}

export interface HighVolumeSource {
  source_ip: string;
  bytes_sent: number;
  gb_sent: number;
}

export interface UnusualProtocols extends SecurityFindingCategory {
  unusual_protocols: any[];
  count: number;
}

export interface ThreatIntelligenceMatches extends SecurityFindingCategory {
  threat_matches: any[];
  total_threat_patterns: number;
  matching_patterns: number;
}

// ===========================================
// RECOMMENDATIONS SECTION
// ===========================================

export interface RecommendationsAndNextSteps {
  prioritized_recommendations: SecurityRecommendation[];
  
  // Optional additional guidance
  further_investigation_areas?: string[];
  security_control_adjustments?: string[];
  user_notes?: string;
}

export interface SecurityRecommendation {
  priority: 'IMMEDIATE' | 'SCHEDULED' | 'ONGOING' | 'LOW';
  category: string;
  finding: string;
  recommendation: string;
  estimated_effort: string;
  timeline: string;
}

// ===========================================
// DATA SOURCES & CONFIGURATION SECTION
// ===========================================

export interface DataSourcesAndConfiguration {
  primary_data_source: string;
  yaf_ipfix_sensors: string[];
  threat_intelligence_sources: string[];
  analysis_methodology: AnalysisMethodology;
  ipfix_information_elements: string[];
  configuration_details: ConfigurationDetails;
}

export interface AnalysisMethodology {
  normal_traffic_analysis: string;
  threat_detection: string;
  comparison_scope: string;
}

export interface ConfigurationDetails {
  sampling_rate: string;
  flow_timeout: string;
  collection_method: string;
}

// ===========================================
// COMPLIANCE & GOVERNANCE SECTION
// ===========================================

export interface ComplianceAndGovernance {
  data_retention_policy: string;
  privacy_controls: string;
  access_controls: string;
  audit_trail: string;
}

// ===========================================
// AI ANALYSIS SECTION
// ===========================================

export interface AIAnalysis {
  finding: string;
  attack_technique: string;
  confidence_score: number;
  business_impact: string;
  recommended_action: string;
  timeline: string;
}

// ===========================================
// API RESPONSE WRAPPERS
// ===========================================

/**
 * API response wrapper for report data
 */
export interface ReportApiResponse {
  success: boolean;
  report: ReportData;
  message?: string;
  error?: string;
}

/**
 * Alternative API response structure
 */
export interface AlternativeReportResponse {
  reportData: ReportData;
  reportId: string;
}

// ===========================================
// UTILITY TYPES
// ===========================================

/**
 * Severity levels used throughout the application
 */
export type SeverityLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/**
 * Priority levels for recommendations and actions
 */
export type PriorityLevel = 'IMMEDIATE' | 'SCHEDULED' | 'ONGOING' | 'LOW';

/**
 * Report generation types
 */
export type ReportGenerationType = 'scheduled' | 'user_requested' | 'manual';

/**
 * Risk levels for overall assessment
 */
export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

// ===========================================
// VALIDATION HELPERS
// ===========================================

/**
 * Type guard to check if data has the expected report structure
 */
export function isValidReportData(data: any): data is ReportData {
  return (
    data &&
    typeof data === 'object' &&
    data.metadata &&
    data.executive_summary &&
    data.network_traffic_overview &&
    data.security_findings &&
    data.recommendations_and_next_steps
  );
}

/**
 * Type guard to check if response is wrapped in API format
 */
export function isApiResponse(data: any): data is ReportApiResponse {
  return data && typeof data === 'object' && 'success' in data && 'report' in data;
}

/**
 * Extract report data from various response formats
 */
export function extractReportData(data: any): ReportData | null {
  // Direct report data
  if (isValidReportData(data)) {
    return data;
  }
  
  // API response wrapper
  if (isApiResponse(data) && data.success && isValidReportData(data.report)) {
    return data.report;
  }
  
  // Alternative wrapper
  if (data.reportData && isValidReportData(data.reportData)) {
    return data.reportData;
  }
  
  // Legacy structure
  if (data.content && typeof data.content === 'string') {
    try {
      const parsed = JSON.parse(data.content);
      if (isValidReportData(parsed)) {
        return parsed;
      }
    } catch {
      // Invalid JSON, continue
    }
  }
  
  return null;
}

// ===========================================
// DEFAULT VALUES
// ===========================================

/**
 * Default values for missing report sections
 */
export const DEFAULT_REPORT_VALUES = {
  metadata: {
    report_title: 'Security Report',
    reporting_period: '',
    generated_by: 'LEVANT AI Security Platform',
    generation_date: new Date().toISOString(),
    report_version: '3.0',
    analysis_duration_hours: 24,
    analysis_scope: 'Network security analysis',
    threat_detection_method: 'Pattern matching and AI analysis',
  },
  
  executive_summary: {
    overall_risk_level: 'MEDIUM' as RiskLevel,
    key_findings: ['Security analysis completed'],
    critical_issues_count: 0,
    recommendations_priority: 'SCHEDULED' as PriorityLevel,
  },
  
  basic_stats: {
    total_flows: 0,
    total_bytes: 0,
    total_packets: 0,
    avg_duration: 0,
  },
} as const; 