#!/bin/bash

# Reset Cybersecurity Reports Directory
# This script cleans up all existing reports and creates a fresh directory structure
# for new installations or testing purposes.

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORTS_DIR="$PROJECT_DIR/cybersecurity_reports"

echo "🧹 Resetting cybersecurity reports directory..."
echo "📁 Project directory: $PROJECT_DIR"
echo "📊 Reports directory: $REPORTS_DIR"

# Confirm action
read -p "⚠️  This will delete ALL existing reports. Continue? (y/N): " confirm
if [[ ! $confirm =~ ^[Yy]$ ]]; then
    echo "❌ Operation cancelled."
    exit 0
fi

# Backup one sample report if any exist
echo "💾 Creating sample backup..."
if find "$REPORTS_DIR" -name "*.json" -type f | head -1 | read -r sample_file; then
    mkdir -p "$REPORTS_DIR/samples"
    cp "$sample_file" "$REPORTS_DIR/samples/sample_report.json" 2>/dev/null || true
    echo "✅ Sample report backed up: samples/sample_report.json"
else
    echo "ℹ️  No existing reports found to backup"
fi

# Remove all existing reports and directories
echo "🗑️  Removing existing reports..."
rm -rf "$REPORTS_DIR/shared"/* 2>/dev/null || true
rm -rf "$REPORTS_DIR/users"/* 2>/dev/null || true  
rm -rf "$REPORTS_DIR/admin"/* 2>/dev/null || true

# Recreate clean directory structure
echo "📁 Creating clean directory structure..."
mkdir -p "$REPORTS_DIR/shared"
mkdir -p "$REPORTS_DIR/users"
mkdir -p "$REPORTS_DIR/admin"
mkdir -p "$REPORTS_DIR/samples"

# Create README files
echo "📝 Creating documentation..."

cat > "$REPORTS_DIR/README.md" << 'EOF'
# Cybersecurity Reports Directory

This directory contains generated cybersecurity analysis reports from the LEVANT AI Security Platform.

## Directory Structure

- **`shared/`** - Reports accessible to all users across the organization
- **`users/`** - User-specific reports organized by username/role  
- **`admin/`** - Administrative reports with elevated access
- **`samples/`** - Sample report templates and examples

## Report Generation

Reports are automatically generated by the system and can be triggered through:
- The web interface at `/reports`
- API endpoint `/api/reports/generate`
- Scheduled automated scans

## File Naming Convention

Reports follow the naming pattern:
```
{type}_report_{duration}_{timestamp}.json
```

Example: `cybersecurity_report_3.5h_20250715_153224.json`

## Getting Started

New installations will have empty directories. Generate your first report through the web interface to get started.
EOF

cat > "$REPORTS_DIR/shared/README.md" << 'EOF'
# Shared Reports

This directory contains cybersecurity reports that are accessible to all users in the organization.

Reports placed here are typically:
- System-wide security analysis
- Network overview reports  
- Organization-level threat assessments
- Scheduled automated reports

Generate new shared reports through the web interface or API.
EOF

cat > "$REPORTS_DIR/users/README.md" << 'EOF'
# User Reports

This directory contains user-specific cybersecurity reports organized by username or role.

## Structure
Each user has their own subdirectory:
```
users/
├── username1/
├── username2/
└── role_name/
```

## Report Types
- Personal security scans
- User-specific threat analysis  
- Custom reports generated by individual users
- Access-controlled reports

Users can only access reports in their own directories unless given elevated permissions.
EOF

cat > "$REPORTS_DIR/admin/README.md" << 'EOF'
# Administrative Reports

This directory contains administrative-level cybersecurity reports with elevated access requirements.

## Report Types
- System administrative reports
- Security audit results
- Compliance and regulatory reports
- High-privilege security analysis
- Infrastructure monitoring reports

Access to this directory requires administrative privileges.
EOF

# Final verification
REPORT_COUNT=$(find "$REPORTS_DIR" -name "*.json" | wc -l)
echo ""
echo "✅ Reports directory reset completed!"
echo "📊 Directory structure:"
echo "   - shared/     (empty)"
echo "   - users/      (empty)" 
echo "   - admin/      (empty)"
echo "   - samples/    (1 backup report)"
echo "📄 Remaining JSON files: $REPORT_COUNT"
echo ""
echo "🚀 Ready for new report generation!"
echo "   - Visit the web interface at /reports"
echo "   - Use API: POST /api/reports/generate"
echo "" 