import { NextRequest, NextResponse } from "next/server";
import neo4jService from "@/lib/neo4j-service";

function getUserFromSession(request: NextRequest): { netId: string; role: string } | null {
  try {
    const sessionCookie = request.cookies.get('duke-sso-session');
    if (!sessionCookie) return null;
    
    const sessionData = JSON.parse(Buffer.from(sessionCookie.value, 'base64').toString());
    if (Date.now() > sessionData.expires) return null;
    
    const user = sessionData.user;
    const netId = user.eppn ? user.eppn.split('@')[0] : user.netId || 'unknown';
    const role = user.affiliation ? (
      user.affiliation.includes('faculty') ? 'faculty' :
      user.affiliation.includes('staff') ? 'staff' : 'student'
    ) : user.role || 'student';
    
    return { netId, role };
  } catch {
    return null;
  }
}

export async function GET(request: NextRequest) {
  try {
    const url = new URL(request.url);
    const reportId = url.searchParams.get('id');
    const format = url.searchParams.get('format') || 'json';

    if (!reportId) {
      return NextResponse.json({ error: 'Report ID is required' }, { status: 400 });
    }

    // Get user from session
    const user = getUserFromSession(request);
    if (!user) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    try {
      // Get report from Neo4j
      const allowAdmin = user.role === 'faculty' || user.role === 'staff';
      const report = await neo4jService.getReport(reportId, user.netId, allowAdmin);
      
      if (!report) {
        return NextResponse.json({ error: 'Report not found' }, { status: 404 });
      }

      // Parse content if it's a string
      const reportData = {
        ...report,
        content: typeof report.content === 'string' ? JSON.parse(report.content) : report.content
      };
      
      if (format === 'json') {
        // Return JSON download
        const headers = new Headers();
        headers.set('Content-Type', 'application/json');
        headers.set('Content-Disposition', `attachment; filename="${reportId}.json"`);
        
        const downloadData = {
          id: reportData.id,
          name: reportData.name,
          type: reportData.type,
          content: reportData.content,
          metadata: {
            ...reportData.metadata,
            generated_by: reportData.generatedBy?.displayName,
            generated_at: reportData.generatedAt,
            risk_level: reportData.riskLevel,
            threat_count: reportData.threatCount,
            critical_issues: reportData.criticalIssues
          }
        };
        
        return new NextResponse(JSON.stringify(downloadData, null, 2), { headers });
      } 
      
      if (format === 'summary') {
        // Return a formatted summary
        const summary = generateReportSummary(reportData);
        const headers = new Headers();
        headers.set('Content-Type', 'text/plain');
        headers.set('Content-Disposition', `attachment; filename="${reportId}_summary.txt"`);
        
        return new NextResponse(summary, { headers });
      }

      return NextResponse.json({ error: 'Unsupported format' }, { status: 400 });
    } catch (error) {
      console.error('Error fetching report from Neo4j:', error);
      return NextResponse.json({ error: 'Error reading report' }, { status: 500 });
    }
  } catch (error) {
    console.error('Error in download API:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

function generateReportSummary(reportData: any): string {
  const content = reportData.content || {};
  const metadata = content.metadata || {};
  const executiveSummary = content.executive_summary || {};
  const networkOverview = content.network_traffic_overview?.basic_stats || {};

  return `
CYBERSECURITY REPORT SUMMARY
============================

Report Details:
- Title: ${reportData.name || metadata.report_title || 'Untitled Report'}
- Type: ${reportData.type || metadata.report_type || 'Unknown'}
- Generated: ${reportData.createdAt ? new Date(reportData.createdAt).toLocaleString() : 'Unknown'}
- Generated By: ${reportData.generatedBy?.displayName || metadata.generated_by || 'Unknown'}
- Risk Level: ${reportData.riskLevel || executiveSummary.overall_risk_level || 'Unknown'}

Security Metrics:
- Total Threats: ${reportData.threatCount || executiveSummary.total_threats_detected || 0}
- Critical Issues: ${reportData.criticalIssues || executiveSummary.critical_issues || 0}
- Risk Score: ${reportData.riskScore || 'N/A'}/10

Network Statistics:
- Total Flows: ${reportData.networkFlows || networkOverview.total_flows || 0}
- Data Analyzed: ${reportData.dataBytes ? (reportData.dataBytes / 1024 / 1024).toFixed(2) + ' MB' : networkOverview.total_bytes || 'N/A'}
- Average Bandwidth: ${reportData.avgBandwidth || networkOverview.avg_bandwidth || 'N/A'} Mbps

Key Findings:
${reportData.findings ? reportData.findings.map((f: string, i: number) => `${i + 1}. ${f}`).join('\n') : 'No specific findings recorded'}

Recommendations:
${reportData.recommendations ? reportData.recommendations.map((r: string, i: number) => `${i + 1}. ${r}`).join('\n') : 'No specific recommendations recorded'}

Generated on: ${new Date().toLocaleString()}
  `.trim();
} 